name: Build thel library
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libohp.so
          path: target/release/libohp.so

